<h1 style="color:green" align='center'>Numpy tutorial: iterate numpy array using nditer</h1>

In [1]:
import numpy as np

In [6]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<h3 style="color:purple">Using normal for loop iteration</h3>

In [8]:
for row in a:
    print(row)
    for cell in row:
        print(cell)

[0 1 2 3]
0
1
2
3
[4 5 6 7]
4
5
6
7
[ 8  9 10 11]
8
9
10
11


<h3 style="color:purple">For loop with flatten</h3>

In [9]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


<h1 style="color:blue" align="center">nditer</h1>

<h3 style="color:purple">C style ordering</h3>

In [43]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [44]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
4
9
16
25
36
49
64
81
100
121


<h2 style="color:purple">Fortan style ordering</h2>

In [45]:
for x in np.nditer(a, order='F'):
    print(x)

0
16
64
1
25
81
4
36
100
9
49
121


<h3 style="color:purple">external_loop</h3>

In [46]:
for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

[ 0 16 64]
[ 1 25 81]
[  4  36 100]
[  9  49 121]


<h2 style="color:purple">Modify array values while iterating</h2>

In [47]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [48]:
a

array([[    0,     1,    16,    81],
       [  256,   625,  1296,  2401],
       [ 4096,  6561, 10000, 14641]])

<h2 style="color:purple">Iterate two broadcastable arrays concurrently</h2>

In [49]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [50]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
16 3
81 3
256 7
625 7
1296 7
2401 7
4096 11
6561 11
10000 11
14641 11


In [51]:
np.array([
    [1, 2]
]) + np.array([
    [1, 2]
])

array([[2, 4]])

In [52]:
[1, 2] + [1, 2]

[1, 2, 1, 2]